const benefits = [
  {
    icon: '🤖',
    title: 'AI-Powered Designs',
    desc: 'Instant 3D design concepts generated by AI trained on thousands of successful projects — reviewed by engineers before delivery.',
    color: 'border-blue-200 bg-blue-50',
    iconBg: 'bg-blue-100',
  },
  {
    icon: '🖥️',
    title: 'Real-Time 3D Preview',
    desc: 'See every material, furniture piece and lighting scenario in photo-realistic 3D before a single rupee is spent on manufacturing.',
    color: 'border-purple-200 bg-purple-50',
    iconBg: 'bg-purple-100',
  },
  {
    icon: '💰',
    title: 'Instant Accurate Costing',
    desc: 'AI cost engine with live market pricing gives BOQ accurate to ±5%. No hidden charges, no surprises. Ever.',
    color: 'border-green-200 bg-green-50',
    iconBg: 'bg-green-100',
  },
  {
    icon: '🏭',
    title: 'In-House Manufacturing',
    desc: 'Your furniture is precision-manufactured in our own factory — no third-party middlemen, tighter quality control, faster turnaround.',
    color: 'border-orange-200 bg-orange-50',
    iconBg: 'bg-orange-100',
  },
  {
    icon: '📱',
    title: 'Real-Time Installation Tracking',
    desc: 'GPS-tracked dispatch, daily installation progress photos and live dashboard. Know exactly where your project is, every day.',
    color: 'border-teal-200 bg-teal-50',
    iconBg: 'bg-teal-100',
  },
  {
    icon: '🛡️',
    title: '5-Year Warranty',
    desc: 'Comprehensive warranty on all workmanship and manufactured items. Annual maintenance visits included in the first year.',
    color: 'border-red-200 bg-red-50',
    iconBg: 'bg-red-100',
  },
]

export default function WhyChooseUs() {
  return (
    <section id="about" className="py-24 bg-white">
      <div className="max-w-7xl mx-auto px-6 lg:px-10">

        {/* Header */}
        <div className="grid lg:grid-cols-2 gap-12 items-center mb-16">
          <div>
            <span className="section-label">Why El Shaddai</span>
            <h2 className="section-title mt-3 mb-5">
              50 Years of Engineering <br />
              <span className="text-gold-gradient font-medium">Meets Modern AI</span>
            </h2>
            <p className="font-body text-stone-500 text-sm leading-relaxed mb-6">
              El Shaddai was founded by engineers with over 50 combined years of experience in construction, manufacturing and interior design. We built our AI platform not to replace that expertise — but to amplify it and make it accessible to every Indian homeowner.
            </p>
            <div className="flex items-center gap-4 p-5 bg-navy-50 border border-navy-100 rounded-sm">
              <div className="text-4xl">👷</div>
              <div>
                <p className="font-body font-semibold text-navy-900 text-sm">Engineer-Founded & Led</p>
                <p className="font-body text-stone-500 text-xs mt-0.5">Our senior team holds degrees in Civil, Mechanical and Interior Architecture Engineering — with site experience across 15 cities.</p>
              </div>
            </div>
          </div>

          {/* Image */}
          <div className="relative">
            <div className="img-zoom rounded-sm overflow-hidden h-80 lg:h-96">
              <img
                src="https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=800&q=80"
                alt="El Shaddai engineering team"
                className="w-full h-full object-cover"
              />
            </div>
            {/* Experience badge */}
            <div className="absolute -bottom-5 -left-5 bg-navy-950 text-white p-5 rounded-sm shadow-xl">
              <div className="font-display text-5xl text-gold-400 font-light leading-none">50+</div>
              <div className="font-body text-white/70 text-xs tracking-wide uppercase mt-1">Years<br />Experience</div>
            </div>
            {/* Projects badge */}
            <div className="absolute -top-4 -right-4 bg-gold-500 text-white p-4 rounded-sm shadow-xl">
              <div className="font-display text-3xl font-light leading-none">2400+</div>
              <div className="font-body text-white/80 text-[10px] tracking-wide uppercase mt-0.5">Projects<br />Delivered</div>
            </div>
          </div>
        </div>

        {/* Benefits grid */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {benefits.map((b, i) => (
            <div key={i} className={`p-6 rounded-sm border ${b.color} group hover:shadow-md transition-all duration-300`}>
              <div className={`w-12 h-12 ${b.iconBg} rounded-sm flex items-center justify-center text-2xl mb-4 group-hover:scale-110 transition-transform duration-300`}>
                {b.icon}
              </div>
              <h3 className="font-display text-xl text-navy-950 font-medium mb-2">{b.title}</h3>
              <p className="font-body text-sm text-stone-500 leading-relaxed">{b.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
